name: Deployment pipeline
run-name: Deployment
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  "pre-production":
    runs-on: ubuntu-latest
    environment: "pre-production"
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "Deploying to ${{ vars.ENV }}..."
      - run: echo "Done."
      - name: Tag commit
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.date.outputs.date }}-deployed-pre-production",
              sha: context.sha
            })
      - run: echo "Running tests..."
      - run: echo "Done."

  "production-eu":
    needs: "pre-production"
    runs-on: ubuntu-latest
    environment: "production-eu"
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "Deploying to ${{ vars.ENV }}..."
      - run: echo "Done."
      - name: Tag commit
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.date.outputs.date }}-deployed-production-eu",
              sha: context.sha
            })

  "production-gate-a":
    needs: "production-eu"
    environment: "production-gate-a"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Enabling next wave of production deployments..."

  "production-us":
    needs: "production-gate-a"
    runs-on: ubuntu-latest
    environment: "production-us"
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "Deploying to ${{ vars.ENV }}..."
      - run: echo "Done."
      - name: Tag commit
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.date.outputs.date }}-deployed-production-us",
              sha: context.sha
            })
  "production-jp":
    needs: "production-gate-a"
    runs-on: ubuntu-latest
    environment: "production-jp"
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      - run: echo "Deploying to ${{ vars.ENV }}..."
      - run: echo "Done."
      - name: Tag commit
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.date.outputs.date }}-deployed-production-jp",
              sha: context.sha
            })