name: Deployment pipeline
run-name: Deployment
on:
  push:
    branches:
      - main
jobs:
  "pre-production":
    runs-on: ubuntu-latest
    environment: "pre-production"
    steps:
      - run: echo "Deploying to ${{ env.env }}..."
      - run: echo "Done."
      - run: echo "Running tests..."
      - run: echo "Done."

  "production-eu":
    needs: "pre-production"
    runs-on: ubuntu-latest
    environment: "production-eu"
    steps:
      - run: echo "Deploying to ${{ env.env }}..."
      - run: echo "Done."
      - run: echo "Monitoring health..."
      - run: echo "Done."

  "production-gate-a":
    needs: "production-eu"
    environment: "production-gate-a"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Enabling next wave of production deployments..."

  "production-us":
    needs: "production-wave-2"
    runs-on: ubuntu-latest
    environment: "production-us"
    steps:
      - run: echo "Deploying to ${{ env.env }}..."
      - run: echo "Done."
      - run: echo "Monitoring health..."
      - run: echo "Done."
  "production-jp":
    needs: "production-wave-2"
    runs-on: ubuntu-latest
    environment: "production-jp"
    steps:
      - run: echo "Deploying to ${{ ENVIRONMENT.ENV }}..."
      - run: echo "Done."
      - run: echo "Monitoring health..."
      - run: echo "Done."